name: Publish to Crates.io

on:
  workflow_dispatch:
jobs:
  formatting:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run fmt check
        run: cargo +nightly fmt --all --check
  sanity:
    name: Sanity Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run clippy check
        run: cargo clippy -- -D warnings
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Run cargo audit
        run: cargo audit -D warnings
  dry-run:
    name: Dry run publish
    needs: [sanity, formatting]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Publish Dry run
        run: cargo publish --dry-run
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [sanity, dry-run]
    environment:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO__TOKEN }}
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cargo login
        run: cargo login
      - name: Publish
        run: cargo publish
